language: go
go:
- 1.14.4
install:
- go get golang.org/x/tools/cmd/cover
- go get -v github.com/axw/gocov/gocov
- go get -v github.com/mattn/goveralls
- go get -t
script:
- go test -race -v -covermode=atomic -coverprofile=profile_tmp github.com/getlantern/proxy/... && tail -n +2 profile_tmp >> profile.cov && tail -n +2 profile_tmp >> profile.cov
after_success:
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
